# .do/app.yaml
name: bussiness-loans-github
region: sgp
services:
  - name: bussiness-loans-github
    http_port: 3001
    build_command: npm install && cd frontend && npm run build:production
    run_command: npm run start:prod
    source_dir: /
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3001"
    health_check:
      http_path: /api/health
