export enum LeadComputedStatus {
  NEW = "NEW",
  IN_PROGRESS = "IN_PROGRESS",
  WON = "WON",
  WITHDRAWN = "WITHDRAWN",
  REJECTED = "REJECTED",
  NO_RESPONSE = "NO_RESPONSE",
  WAITING_OUTCOME = "WAITING_OUTCOME",
  NO_ACTIVITY = "NO_ACTIVITY",
}
