export const TEST_IDS = {
  manualApplicationButton: "manual-application-button",
  borrowAmountSlider: "borrow-amount-slider",
  borrowTermSlider: "borrow-term-slider",
  borrowAgeSlider: "borrow-age-slider",
  borrowPurposeSelect: "borrow-purpose-select",
  nricInput: "nric-input",
  residencyStatusBox: "residency-status-box",
  monthlyIncomeInput: "monthly-income-input",
  occupationalStatusSelect: "occupational-status-select",
  jobTitleInput: "job-title-input",
  currentEmploymentTimeSelect: "current-employment-time-select",
  previousEmploymentTimeSelect: "previous-employment-time-select",
  propertyOwnershipSelect: "property-ownership-select",
  postalCodeInput: "postal-code-input",
  existingLoanBox: "existing-loan-box",
  fullNameInput: "full-name-input",
  phoneNumberInput: "phone-number-input",
  emailAddressInput: "email-address-input",
  otpInput: "otp-input",
  submitOtpButton: "submit-otp-button",

  nextStepButton: "next-step-button",
};
