name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: dop_v1_20aef5874213e083ca157b34a8a749a5e65097f2e8eb56faa0f783b6bfc7986b

      - name: Deploy to DigitalOcean App Platform
        run: doctl apps create-deployment 6f771ee3-2b1e-4ba6-8b2d-7aa607d7c05c --wait
